### ISSUE TITLE
部署SSL后，wordpress不能准确获取访客真实IP，但http下可以获取

### ISSUE THREAD

**Issue by max-sherry** [renbaoshuo/baoshuo-blog#15]
大佬你好，我现在用的是樱花日本东京节点，armbian+nginx1.10.3+php7.4，自己用WP搭建了一个简单的博客，我之前用http访问网址，WP可以正常获取访客IP，但是我部署了SSL之后，WP就不能识别访客IP了，只显示127.0.0.1，请问我该怎么设置呢？

**Comment by renbaoshuo** [comment]
你这来错地方了吧，再次重申：**本人不是 Sakura Frp 的管理员，有关问题请前往 [OWQ](https://owq.moe/channel/Natfrp) 咨询。**

2020/07/30 23:13  - 已将此 issue 关闭
